install.packages(c(
    "devtools",
    "mvtnorm",
    "tmvtnorm",
    "plotly",
    "DT",
    "BiocManager",
    "testthat",
    "RColorBrewer",
    "shiny",
    "shinyalert",
    "shinydashboard",
    "shinyjs",
    "svglite"
  ),
  dependencies=TRUE,
  repos="http://cran.rstudio.com/"
)

BiocManager::install(pkgs=c(
    "imputeLCMD",
    "pcaMethods",
    "SummarizedExperiment",
    "ComplexHeatmap"
  ),
  ask=FALSE
)

BiocManager::install(pkgs=c(
    "limma",
    "DEP"
  ),
  ask=FALSE
)
